#!/usr/bin/python3
#SPDX-FileCopyrigtText: 2024 Takeru Yoshida
#SPDX-License-Identifier: BSD-3-Clause

import random
import os

def number_guessing_game():
    print("ランダム数当てゲーム！１か２を入力してください。連続で当てた回数を計測します！")
    consecutive_correct = 0

    while True:
        #ランダムに１か２を生成
        if "TEST_RANDOM" in os.environ:
            random_number = int(os.environ["TEST_RANDOM"])
        else:
            random_number = random.randint(1,2)

        try:
            user_guess = int(input("あなたの予想（１か２）："))
            if user_guess not in [1,2]:
                print("１か２を入力してください！")
                continue

            if user_guess == random_number:
                consecutive_correct += 1
                print(f"正解！現在の連続回数：{consecutive_correct}")
            else:
                print(f"不正解！ランダム数は{random_number}でした。")
                print(f"最終的な連続正解数は{consecutive_correct}でした。")
                break
        except ValueError:
            print("エラー：１または２の数字を入力してください")

if __name__ == "__main__":
    number_guessing_game()
