#!/usr/bin/python3
#SPDX-FileCopyrightText: 2024 Takeru Yoshida 
#SPDX-License-Identifier: BSD-3-Clause

import random



def number_guessing_game():
    print("数宛ゲームを始めます！1～50の間の数を入力してください")
    random_number = random.randint(1,50) #1~50の中の数字を生成する
    attempts = 0

    while True:
        try:
           user_guess = int(input("あなたの予想："))
           attempts += 1

           if user_guess < random_number:
               print("もうちょい大きい！")

           elif user_guess > random_number:
               print("もうちょい小さい！")

           else:
               print(f"正解です！ {attempts}回目で当たりました！")
               break
        except ValueError:
            print("エラー：数字を入力してください")


number_guessing_game()
